# CI/CD Pipeline for Build, Test, Package, and Publish
name: Build-Test-Package-Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup XVFB and Headless Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb chromium-browser
          sudo Xvfb :99 -ac &
          export DISPLAY=:99
          export CHROME_BIN=chromium-browser

      - run: npm ci
      - run: npm run test
        env:
          CHROME_BIN: chromium-browser
          DISPLAY: :99

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: servicestack-vue
          path: |
            ./dist/servicestack-vue.mjs
            ./dist/servicestack-vue.min.mjs
            ./dist/servicestack-vue.umd.cjs

  publish:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Bump version
        run: |
          VERSION=$(jq -r '.version' package.json)
          HASH=$(git rev-parse --short HEAD)
          NEW_VERSION="$VERSION-preview-$HASH"
          jq --arg nv "$NEW_VERSION" '.version=$nv' package.json > "tmp.json" && mv "tmp.json" "package.json"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
